name: Deploy and Tag Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node.js Dependencies
        run: npm install
        working-directory: ./path-to-your-angular-app

      - name: Build Angular App
        run: npm run build
        working-directory: ./path-to-your-angular-app

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Java App
        run: mvn clean package
        working-directory: ./path-to-your-java-app

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Add your deployment commands here

      - name: Get Current Version
        id: get_version
        run: |
          VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Current version: $VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: Increment Version
        id: increment_version
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
          PATCH_VERSION=$((VERSION_PARTS[2] + 1))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH_VERSION"
          echo "New version: $NEW_VERSION"
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"

      - name: Create Release Tag
        run: |
          NEW_VERSION=${{ steps.increment_version.outputs.NEW_VERSION }}
          git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
          git push origin "$NEW_VERSION"